name: Build CLI Tool

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache-dependency-path: tools/go.sum

      - name: Build CLI
        run: |
          cd tools
          go build -o tools-cli ./cmd/tools-cli

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tools-cli-artifact
          path: tools/tools-cli
