name: "Manual Re-index and Deploy"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build-tool.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4.3.0
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Download CLI artifact
        uses: actions/download-artifact@v4
        with:
          name: tools-cli-artifact
          path: .
          
      - name: Make CLI executable
        run: chmod +x ./tools-cli

      - name: Package and Generate Index
        run: |
          ./tools-cli package
          ./tools-cli generate-index --cdn-url "https://${{ vars.S3_BUCKET_NAME }}.s3.${{ vars.AWS_REGION }}.amazonaws.com"

      - name: Deploy Content to CDN
        run: |
          aws s3 sync ./dist/ s3://${{ vars.S3_BUCKET_NAME }}/
          aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"