name: PR Review

on:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build-tool.yml

  review:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download CLI
        uses: actions/download-artifact@v4
        with:
          name: tools-cli-artifact
          path: tools

      - name: Make CLI executable
        run: chmod +x tools/tools-cli

      - name: Get changed files
        id: changed-files
        run: |
          echo "files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | xargs)" >> $GITHUB_OUTPUT

      - name: Validate manifests
        if: contains(steps.changed-files.outputs.files, 'deps/') || contains(steps.changed-files.outputs.files, 'scripts/')
        run: |
          cd tools
          ./tools-cli validate
