name: "PR Review"

on:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build-tool.yml

  review:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download CLI artifact
        uses: actions/download-artifact@v5
        with:
          name: tools-cli-artifact
          path: .

      - name: Make CLI executable
        run: chmod +x ./tools-cli

      - name: Get changed files
        id: changed-files
        run: |
          echo "files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | xargs)" >> $GITHUB_OUTPUT

      - name: "Scenario: New Dependency"
        if: contains(steps.changed-files.outputs.files, 'deps/')
        run: |
          echo "Changes detected in deps/ directory."
          echo "Running validation for deps..."
          ./tools-cli validate --path deps

      - name: "Scenario: New Script"
        if: contains(steps.changed-files.outputs.files, 'scripts/')
        run: |
          echo "Changes detected in scripts/ directory."
          echo "Running validation for scripts..."
          ./tools-cli validate --path scripts